# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Privateer < Formula
  desc ""
  homepage "https://github.com/privateerproj/privateer"
  version "0.0.0"

  on_macos do
    url "https://github.com/privateerproj/privateer/releases/download/v0.0.0/privateer_Darwin_all.tar.gz"
    sha256 "fa1683e7504ffde12d85364aee1793597e65abebc1b5bf506c057ca1da39a6d1"

    def install
      bin.install "privateer"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/privateerproj/privateer/releases/download/v0.0.0/privateer_Linux_arm64.tar.gz"
      sha256 "11b6fbc0a4a2aa4cdbe0b3e1d98851b3adc2f9fae7cb1558fee959f30c0009a9"

      def install
        bin.install "privateer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/privateerproj/privateer/releases/download/v0.0.0/privateer_Linux_x86_64.tar.gz"
      sha256 "f832c538909b075485fa405ce2586faa5a31c540374e92c8d5af779ebbaa2704"

      def install
        bin.install "privateer"
      end
    end
  end
end
