# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Privateer < Formula
  desc ""
  homepage "https://github.com/privateerproj/privateer"
  version "0.0.0-rc"

  on_macos do
    url "https://github.com/privateerproj/privateer/releases/download/v0.0.0-rc/privateer_Darwin_all.tar.gz"
    sha256 "5d0b0dbce01cf9f0c0ac58466a2297193436244b182480c60bf35fc8b8608aa6"

    def install
      bin.install "privateer"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/privateerproj/privateer/releases/download/v0.0.0-rc/privateer_Linux_arm64.tar.gz"
      sha256 "b10edff12c40f0044126a2068d4ca3f635869d5ce27931c26363f0ca4ae0bb6a"

      def install
        bin.install "privateer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/privateerproj/privateer/releases/download/v0.0.0-rc/privateer_Linux_x86_64.tar.gz"
      sha256 "4f03eff1691edcf030a7f8240305de165f3dfd84d93017059b5cb5c3ab7fbb1c"

      def install
        bin.install "privateer"
      end
    end
  end
end
