# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Privateer < Formula
  desc ""
  homepage "https://github.com/privateerproj/privateer"
  version "0.0.0-rc"

  on_macos do
    url "https://github.com/privateerproj/privateer/releases/download/v0.0.0-rc/privateer_Darwin_all.tar.gz"
    sha256 "15025adb1937eba4a637cd9a5979e647abca683efa5ad0cd158470feb7e69c70"

    def install
      bin.install "privateer"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/privateerproj/privateer/releases/download/v0.0.0-rc/privateer_Linux_arm64.tar.gz"
      sha256 "bf8321f7990a2a6a542963bf901db7f8d821b2712873b906b01b44ab325ade91"

      def install
        bin.install "privateer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/privateerproj/privateer/releases/download/v0.0.0-rc/privateer_Linux_x86_64.tar.gz"
      sha256 "6659b95e23ef73f090f3c6d50b35c071d58129c8c8b2dd4f8dc4d56acd484e7f"

      def install
        bin.install "privateer"
      end
    end
  end
end
